"use client"
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type ErrorType = {
  statusCode: string | number
}

function NotFound({ statusCode }: ErrorType): React.JSX.Element {
  return (
      <p>
        {statusCode
            ? `An error ${statusCode} occurred on server`
            : 'An error occurred on client'}
      </p>
  )
}



export default NotFound
